// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbz1KAJ3G4MMfL_zZmUj_2FoTH-1YzLbI',
    appId: '1:1014170192164:web:c1291a405f87f21865cbb1',
    messagingSenderId: '1014170192164',
    projectId: 'fb-backend-68bd1',
    authDomain: 'fb-backend-68bd1.firebaseapp.com',
    storageBucket: 'fb-backend-68bd1.appspot.com',
    measurementId: 'G-2R1K8BKL0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHD5iZ52hEKuOuHc6KdS6RQ4vQGi1FF2I',
    appId: '1:1014170192164:android:ba5bbbf7743f45bf65cbb1',
    messagingSenderId: '1014170192164',
    projectId: 'fb-backend-68bd1',
    storageBucket: 'fb-backend-68bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTUKTiPCsHVMsTI1J7uU1clJ-9KhsKGI',
    appId: '1:1014170192164:ios:aaa5f00bfbc4938f65cbb1',
    messagingSenderId: '1014170192164',
    projectId: 'fb-backend-68bd1',
    storageBucket: 'fb-backend-68bd1.appspot.com',
    iosClientId: '1014170192164-adjcmk7p0hmrakk982je6munqejbk5in.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon2022',
  );
}
